workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    # GANTI 'nama_folder_proyek' dengan nama folder tempat file pubspec.yaml berada
    # Jika pubspec.yaml ada di depan sendiri (root), hapus baris working_directory di bawah ini
    working_directory: . 

    environment:
      groups:
        - signing
      vars:
        PACKAGE_NAME: "com.example.app"
      flutter: stable

    scripts:
      - name: Get dependencies
        script: |
          flutter packages pub get

      - name: Build Android
        script: |
          # Memberikan izin eksekusi pada gradlew
          chmod +x android/gradlew
          
          # Proses compile menjadi APK
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - ficrycahyaramdani@gmail.com      # Kirim notifikasi sukses ke email
