# Konfigurasi Codemagic untuk Aplikasi Sejarah Pahlawan Indonesia (Android Native)
workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    
    environment:
      groups:
        - signing # Pastikan variabel keystore Anda ada di sini
      # Versi Java yang digunakan (biasanya Java 17 untuk proyek Kotlin terbaru)
      vars:
        JAVA_VERSION: "11"

    scripts:
      - name: Build Android APK
        script: |
          #!/usr/bin/env bash
          set -e 

          # 1. Cari file build.gradle untuk menentukan akar proyek
          GRADLE_FILE=$(find . -name "build.gradle" | head -n 1)
          if [ -z "$GRADLE_FILE" ]; then
            echo "ERROR: File build.gradle tidak ditemukan! Pastikan ini adalah proyek Android."
            exit 1
          fi

          # 2. Cari gradlew dan berikan izin eksekusi
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then
            echo "ERROR: gradlew tidak ditemukan."
            exit 1
          fi
          
          PROJECT_ROOT=$(dirname "$GRADLEW_PATH")
          cd "$PROJECT_ROOT"
          chmod +x gradlew
          echo "Bekerja di direktori: $(pwd)"

          # 3. Jalankan perintah kompilasi Android Native
          # Ini akan menghasilkan file APK Release
          ./gradlew assembleRelease

    artifacts:
      # Lokasi standar hasil build APK untuk Android Native
      - "**/build/outputs/apk/release/*.apk"
      - "**/build/outputs/bundle/release/*.aab"

    publishing:
      email:
        recipients:
          - ficrycahyaramdani@gmail.com
