workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      groups:
        - signing
      flutter: stable

    scripts:
      - name: Setup and Build
        script: |
          # 1. Cari di mana pubspec.yaml berada
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" | head -n 1)
          
          if [ -z "$PUBSPEC_PATH" ]; then
            echo "ERROR: pubspec.yaml tetap tidak ditemukan di GitHub!"
            exit 1
          fi

          # 2. Masuk ke folder proyek
          PROJECT_ROOT=$(dirname "$PUBSPEC_PATH")
          cd "$PROJECT_ROOT"
          echo "Bekerja di direktori: $PROJECT_ROOT"

          # 3. Jalankan perintah Flutter
          flutter packages pub get

          # 4. Cari gradlew dan beri izin
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          if [ ! -z "$GRADLEW_PATH" ]; then
            chmod +x "$GRADLEW_PATH"
          fi

          # 5. Build APK
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"

    publishing:
      email:
        recipients:
          - ficrycahyaramdani@gmail.com      # Kirim notifikasi sukses ke email
