workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    
    environment:
      groups:
        - signing
      vars:
        PACKAGE_NAME: "com.example.app"
      flutter: stable

    scripts:
      - name: Get dependencies
        script: |
          # Cari di mana pubspec.yaml berada dan masuk ke folder itu
          PROJECT_ROOT=$(find . -name "pubspec.yaml" -exec dirname {} \;)
          cd $PROJECT_ROOT
          flutter packages pub get

      - name: Build Android
        script: |
          # Cari folder android untuk menjalankan gradlew
          ANDROID_DIR=$(find . -name "android" -type d)
          cd $ANDROID_DIR
          chmod +x gradlew
          
          # Kembali ke root project untuk build flutter
          cd ..
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER

    artifacts:
      - "**/build/app/outputs/flutter-apk/*.apk"
      - "**/build/app/outputs/bundle/release/*.aab"

    publishing:
      email:
        recipients:
          - ficrycahyaramdani@gmail.com      # Kirim notifikasi sukses ke email
