workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.azhar.pahlawannasional"
scripts:
  - name: Build Android
    script: |
      chmod +x gradlew  # <-- Tambahkan baris ini untuk memberi izin akses
      ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
